NAVI:
  NUM_STEPS: 500
  GT_OCC_MAP_TYPE: 'NAV_MESH'
  NUM_STEPS_EXPLORE: 1
  THRESH_REACH: 0.1
  HFOV: 90
  PERCEPTION: 'None' # possible choices 'Anticipation', 'Potential', 'UNet_Potential'
  STRATEGY: 'Optimistic'
  FLAG_VISUALIZE_MIDDLE_TRAJ: False
  D_type: 'Sqrt_R'
  FLAG_VISUALIZE_FRONTIER_POTENTIAL: False

SEM_MAP:
  FLAG_VISUALIZE_EGO_OBS: False

SAVE:
  TESTING_RESULTS_FOLDER: 'output/TESTING_RESULTS_90degree_Optimistic_NAVMESH_MAP_1STEP_500STEPS'
  LARGE_TESTING_RESULTS_FOLDER: 'output/LARGE_TESTING_RESULTS_90degree_Optimistic_NAVMESH_MAP_1STEP_500STEPS'

EVAL:
  SIZE: 'large'
  USE_ALL_START_POINTS: True